### ISSUE TITLE
ERROR: No matching distribution found for JupyterPilot

### ISSUE THREAD

**Issue by Emasoft** [ishu121992/JupyterPilot#1]
Doesn't seem to find the python package.
```
In [1]: !pip install JupyterPilot
ERROR: Could not find a version that satisfies the requirement JupyterPilot (from versions: none)
ERROR: No matching distribution found for JupyterPilot
```

**Comment by ishu121992** [comment]
> 

I am uploading the package shortly on pypi.

**Comment by ishu121992** [comment]
> Doesn't seem to find the python package.
> 
> ```
> In [1]: !pip install JupyterPilot
> ERROR: Could not find a version that satisfies the requirement JupyterPilot (from versions: none)
> ERROR: No matching distribution found for JupyterPilot
> ```

@Emasoft This is resolved. please see readme. Corrected few bugs and renamed packages.
