### ISSUE TITLE
Error importing pysetup - version 0.0.9 installed

### ISSUE THREAD

**Issue by sgatea** [ishu121992/JupyterPilot#4]
**When running the cell to import pysetup:**
from jupyterpilot import pysetup

**the following is returned:**
Traceback (most recent call last):

  File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py:3460 in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  Cell In[11], line 1
    from jupyterpilot import pysetup

  File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyterpilot\pysetup.py:78
    elif re.search(regex, line)
                               ^
SyntaxError: expected ':'

**Comment by ishu121992** [comment]
Have resolved it. Please run pip install --upgrade jupyterpilot. 

https://pypi.org/project/jupyterpilot/0.0.10/

**Comment by ishu121992** [comment]
@sgatea please confirm that it's working now.

**Comment by sgatea** [comment]
Working in 0.0.10. Confirmed.
Many Thanks !
